name: Deploy Dev to NuxtHub

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Ensure NuxtHub module is installed
        run: npx nuxthub@latest ensure

      - name: Deploy to NuxtHub (dev)
        uses: nuxt-hub/action@v3
        with:
          project-key: ${{ secrets.NUXT_HUB_PROJECT_KEY }}
